// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjknudqwxsrieteyasvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqa251ZHF3eHNyaWV0ZXlhc3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDM2MjgsImV4cCI6MjA2NDM3OTYyOH0.5y3HwSMGmU0cXMdwoZVua9RVRUxezAFqiH75Tfeun_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);